name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build main.go

    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.MY_TOKEN }}"
        draft: true
        prerelease: false
        automatic_release_tag: "latest"
        files: |
          main
